[lint]
# from the ruff vscode extension docs: 
# if you're using Ruff to organize imports in VS Code and also expect to run Ruff from the command line, you'll want to 
#enable Ruff's isort rules by adding "I" to your extend-select.
extend-select = ["I"]